# Generated by Django 4.2.16 on 2025-02-23 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_post_tags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="tags",
        ),
        migrations.AddField(
            model_name="post",
            name="tags",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
